"""initial migration

Revision ID: 9cc4b07120b3
Revises: 
Create Date: 2025-05-15 10:48:59.294173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc4b07120b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_time', sa.DateTime(), nullable=False),
    sa.Column('reporter_name', sa.String(length=100), nullable=True),
    sa.Column('reporter_phone', sa.String(length=50), nullable=True),
    sa.Column('reporter_type', sa.String(length=50), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_location_address', sa.String(length=255), nullable=False),
    sa.Column('event_location_longitude', sa.Float(), nullable=True),
    sa.Column('event_location_latitude', sa.Float(), nullable=True),
    sa.Column('alarm_type', sa.String(length=100), nullable=True),
    sa.Column('brief_summary', sa.Text(), nullable=False),
    sa.Column('emergency_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarm_records'))
    )
    op.create_table('dispatch_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['dispatch_units.id'], name=op.f('fk_dispatch_units_parent_id_dispatch_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_units')),
    sa.UniqueConstraint('code', name=op.f('uq_dispatch_units_code'))
    )
    op.create_table('statistics_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=50), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('config_data', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistics_configs')),
    sa.UniqueConstraint('config_name', name=op.f('uq_statistics_configs_config_name'))
    )
    op.create_table('statistics_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statistics_type', sa.String(length=50), nullable=False),
    sa.Column('statistics_date', sa.Date(), nullable=False),
    sa.Column('statistics_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statistics_records'))
    )
    op.create_table('alarm_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dispatch_time', sa.DateTime(), nullable=True),
    sa.Column('receive_time', sa.DateTime(), nullable=True),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('feedback_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_alarm_dispatches_alarm_record_id_alarm_records')),
    sa.ForeignKeyConstraint(['unit_id'], ['dispatch_units.id'], name=op.f('fk_alarm_dispatches_unit_id_dispatch_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarm_dispatches'))
    )
    op.create_table('archived_alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('archive_number', sa.String(length=50), nullable=False),
    sa.Column('archive_type', sa.String(length=20), nullable=False),
    sa.Column('archive_status', sa.String(length=20), nullable=False),
    sa.Column('archive_time', sa.DateTime(), nullable=True),
    sa.Column('archive_reason', sa.Text(), nullable=True),
    sa.Column('archive_operator', sa.String(length=50), nullable=True),
    sa.Column('archive_operator_id', sa.Integer(), nullable=True),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('return_operator', sa.String(length=50), nullable=True),
    sa.Column('return_operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_archived_alarms_alarm_record_id_alarm_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archived_alarms')),
    sa.UniqueConstraint('archive_number', name=op.f('uq_archived_alarms_archive_number'))
    )
    op.create_table('dispatching_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('dispatch_unit_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_dispatching_records_alarm_record_id_alarm_records')),
    sa.ForeignKeyConstraint(['dispatch_unit_id'], ['dispatch_units.id'], name=op.f('fk_dispatching_records_dispatch_unit_id_dispatch_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatching_records'))
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_media_files_alarm_record_id_alarm_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files'))
    )
    op.create_table('police_officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('skills', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['dispatch_units.id'], name=op.f('fk_police_officers_unit_id_dispatch_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_police_officers')),
    sa.UniqueConstraint('badge_number', name=op.f('uq_police_officers_badge_number'))
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_transcriptions_alarm_record_id_alarm_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcriptions'))
    )
    op.create_table('archive_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived_alarm_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archived_alarm_id'], ['archived_alarms.id'], name=op.f('fk_archive_files_archived_alarm_id_archived_alarms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_files'))
    )
    op.create_table('archive_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archived_alarm_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archived_alarm_id'], ['archived_alarms.id'], name=op.f('fk_archive_logs_archived_alarm_id_archived_alarms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archive_logs'))
    )
    op.create_table('dispatch_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_dispatch_groups_alarm_record_id_alarm_records')),
    sa.ForeignKeyConstraint(['leader_id'], ['police_officers.id'], name=op.f('fk_dispatch_groups_leader_id_police_officers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_groups'))
    )
    op.create_table('dispatch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['alarm_dispatches.id'], name=op.f('fk_dispatch_logs_dispatch_id_alarm_dispatches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_logs'))
    )
    op.create_table('dispatch_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('assigned_time', sa.DateTime(), nullable=True),
    sa.Column('accepted_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.Column('cancel_time', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_dispatch_tasks_alarm_record_id_alarm_records')),
    sa.ForeignKeyConstraint(['officer_id'], ['police_officers.id'], name=op.f('fk_dispatch_tasks_officer_id_police_officers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_tasks'))
    )
    op.create_table('handling_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_record_id', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.Column('handling_result', sa.Text(), nullable=True),
    sa.Column('handling_method', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_record_id'], ['alarm_records.id'], name=op.f('fk_handling_records_alarm_record_id_alarm_records')),
    sa.ForeignKeyConstraint(['handler_id'], ['police_officers.id'], name=op.f('fk_handling_records_handler_id_police_officers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handling_records'))
    )
    op.create_table('dispatch_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['dispatch_groups.id'], name=op.f('fk_dispatch_group_members_group_id_dispatch_groups')),
    sa.ForeignKeyConstraint(['officer_id'], ['police_officers.id'], name=op.f('fk_dispatch_group_members_officer_id_police_officers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_group_members'))
    )
    op.create_table('evidence_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handling_record_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handling_record_id'], ['handling_records.id'], name=op.f('fk_evidence_files_handling_record_id_handling_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_files'))
    )
    op.create_table('handling_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handling_record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handling_record_id'], ['handling_records.id'], name=op.f('fk_handling_logs_handling_record_id_handling_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handling_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handling_logs')
    op.drop_table('evidence_files')
    op.drop_table('dispatch_group_members')
    op.drop_table('handling_records')
    op.drop_table('dispatch_tasks')
    op.drop_table('dispatch_logs')
    op.drop_table('dispatch_groups')
    op.drop_table('archive_logs')
    op.drop_table('archive_files')
    op.drop_table('transcriptions')
    op.drop_table('police_officers')
    op.drop_table('media_files')
    op.drop_table('dispatching_records')
    op.drop_table('archived_alarms')
    op.drop_table('alarm_dispatches')
    op.drop_table('statistics_records')
    op.drop_table('statistics_configs')
    op.drop_table('dispatch_units')
    op.drop_table('alarm_records')
    # ### end Alembic commands ###
